[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[dependencies]
uefi = { version = "0.17.0" }
uart_16550 = "0.2.0"
x86_64 = "0.14.10"
